### ISSUE TITLE
Docker error due to glibc version mismatch

### ISSUE THREAD

**Issue by jackyzy823** [mozilla-services/channelserver#106]
Recently updated commit (2fd37e68) cause docker image error:

`/app/bin/channelserver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/bin/channelserver)`

Debian:stretch has glibc 2.24 from `ldd --version`

So debian in Dockerfile should at least be upgraded to buster.

**Comment by jackyzy823** [comment]
For now, users can use `mozilla/channelserver@sha256:01f9251637cc3679b8cf31493569a79a27b41f952d4eb3d5306e1ee8d9d3feea`  to get the previous working one.

**Comment by jrconlin** [comment]
Ok, I have to ask.

Channel server exists as a super-specific use service. It's sole job is to pretty much accept one or two packets, identify their rough source, and allow a message pass-thru for FxA connections. I've stopped doing updates to this mostly because the FxA team is working to integrate it into their own product, so I expect this project to be archived soon.

What are you using this service for?

**Comment by jackyzy823** [comment]
For self-hosting FxA stack.

> FxA team is working to integrate it into their own product

Even though FxA team will have their own implementation, there's no reason to publish a not working docker image to override a working one in this period.
