### ISSUE TITLE
Strings being shown in German

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/channelserver#83]
Firefox Accounts has a bug over here https://github.com/mozilla/fxa/issues/5426 where strings are showing up in German on desktop.  The comments lead to channelserver and JR suggested I file this here.  Please read the linked issue for context

**Comment by jrconlin** [comment]
The problem appears to be that the `Accept-Language` header is either not being processed correctly, or is not being sent to the ChannelServer. Working with @jbuck to isolate what the problem might be. 

It does not appear that either the `Accept-Language` header or the code have changed radically.

I'm a bit curious why the problem is not present on mobile if the header is not being sent over.

**Comment by jbuck** [comment]
I've put up a PR that logs the `Accept-Language` header and also proxies it through to the app but I'm still getting Kanada when I sign in with my iOS device: https://github.com/mozilla-services/cloudops-infra/pull/2489

Logs can be seen with: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%20resource.labels.cluster_name%3D%22channelserver-prod-v1%22%20resource.labels.namespace_name%3D%22prod-channelserver%22%20resource.labels.container_name%3D%22nginx%22%0AjsonPayload.request!%3D%22GET%20%2F__lbheartbeat__%20HTTP%2F1.1%22;timeRange=2020-09-15T16:27:38.851Z%2F2020-09-15T16:34:38.851Z;summaryFields=jsonPayload%252FFields%252Fmsg,jsonPayload%252Faccept_language:false:32:beginning?folder=true&organizationId=true&project=moz-fx-channelserve-prod-c549&query=%0A

**Comment by tublitzed** [comment]
@jrconlin when you have a chance (no rush this week I know you're busy) can you detail what you found here? I'd like to try to sort out whether we think the optimal fix here should be done client vs server side.

**Comment by jrconlin** [comment]
Well, the "fix" is fairly straightforward, but I'm not sure it's best.

The problem is that if there's no "Accept-Language" header, or if the value is blank, then No Language Preference is provided to the geolocation library. This results in the first language (determined internally as "de"utsch) to be used. One potential fix is to just default "en" if no language is specified. That would solve this specific view of the problem, but is just as terrible as defaulting to German. 

It's my understanding that this problem is inherent in iOS WebKit and that [a workaround](https://github.com/mozilla/fxa/issues/5426#issuecomment-692845131) could be performed on the client. It would probably be better to solve this on the client than the server since the client has more knowledge about specific user preferences.

**Comment by jrconlin** [comment]
Based off of discussions, I've added a PR to enforce the default language to `en`.

I think the problem may have also been that `-` was not being filtered out as an invalid value.

**Comment by vasilicatamas** [comment]
@jrconlin should this fix already be available for testing in stage? Because I still see the location as being written in Germen.

**Comment by jbuck** [comment]
@vasilicatamas Hmm, I wonder if the stage FxA uses the prod channelserver... that'd explain why the fix isn't present yet

**Comment by jbuck** [comment]
To answer my own question, the answer is 'yes':

```
projects/fxa/puppet/yaml/type/fxa.content_server.dev.yaml
27:fxa_content::pairing_server_base_uri: wss://dev.channelserver.nonprod.cloudops.mozgcp.net

projects/fxa/puppet/yaml/type/fxa.content_server.prod.yaml
27:fxa_content::pairing_server_base_uri: wss://channelserver.services.mozilla.com

projects/fxa/puppet/yaml/type/fxa.content_server.stage.yaml
45:fxa_content::pairing_server_base_uri: wss://channelserver.services.mozilla.com
```

I can change this config, but do we need to change something in Firefox to use the stage channel server as well?

**Comment by rfk** [comment]
> I can change this config, but do we need to change something in Firefox to use the stage channel server as well?

Firefox should use whatever URL is advertized in the client-config document:

 * https://accounts.stage.mozaws.net/.well-known/fxa-client-configuration

**Comment by jbuck** [comment]
@rfk excellent, thanks for checking that!

@vasilicatamas I will update this bug when fxa stage is pointing at channelserver stage

**Comment by jbuck** [comment]
PR up in https://github.com/mozilla-services/cloudops-deployment/pull/4046

**Comment by jbuck** [comment]
@vasilicatamas stage fxa is pointing at stage channelserver now

**Comment by vasilicatamas** [comment]
Thanks @jbuck! I confirm that the location is no longer translated in German. Tested on FxA Stage [Train 1.191.1] under Windows 10 64-bit.
![Screenshot_25](https://user-images.githubusercontent.com/18114210/95588959-bd9e6a00-0a4c-11eb-984f-a1a2502348a4.png)

**Comment by vasilicatamas** [comment]
@jbuck Do you have any idea about when this fix will land in production? Because it seems that it isn't yet in FxA Prod Train 1.191.1.

![Screenshot_36](https://user-images.githubusercontent.com/18114210/95969636-a62dfb00-0e17-11eb-9495-cdc07444ed7e.png)

**Comment by jrconlin** [comment]
Ah, normally QA submits a bugzilla ticket whenever the channelserver passes testing. I'm guessing that this didn't happen, probably due to the various confusion around who has channelserver support now.

IIRC: The ticket should be filed under `Cloud Services`; `Operations: Sync` with a title like: `Please deploy Channelserver 1.0.0 to PROD`. I've taken the liberty of [filing that bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1671216), please adjust as need be.

**Comment by jbuck** [comment]
@vasilicatamas channelserver 1.0 is now deployed in production

**Comment by vasilicatamas** [comment]
I confirm that the location is no longer translated in German on FxA Prod [Train 1.192.0] under Windows 10 64-bit.

![Screenshot_29](https://user-images.githubusercontent.com/18114210/97696604-7e44c580-1aae-11eb-83bb-39818ea4695d.png)
